### ISSUE TITLE
missing bokeh plot for David Silva?

### ISSUE THREAD

**Issue by jeski** [antoniaelek/fantasy-premier-league#1]
Hi, I really love what you've done here. Leveraging vaastav's data and using ipython & bokeh is quite clever.  Wonderful work.  I've looked, but don't seem to be able to find any plot for David Silva.  The text for Silva is available and looking through the data I know it's there.  Could there be an error in the bokeh js? 

It's not really an issue, just thought I'd mention it.

**Comment by antoniaelek** [comment]
Hi @jeski, 

Thanks for notifying me of this. It was a bug in displaying value-per-cost ratios, which is now fixed and hopefully all the data sould now be out there.

I'm glad you like this little fpl thingy. 😃

**Comment by jeski** [comment]
cheers, I absolutely love it.  I take it that you play FPL, then?

**Comment by antoniaelek** [comment]
Yeah, I absolutely love it! But I'm average at best and I'm hoping these analysis will help me to get better at it. 🤣 Obviously you're playing, too since you're interested in it?

**Comment by jeski** [comment]
yeah,  I'm obsessed with it.
