### ISSUE TITLE
Vaastav has updated for the api changes, perhaps it's time to do the same?

### ISSUE THREAD

**Issue by jeski** [antoniaelek/fantasy-premier-league#6]
Hi Antonia, hope you are well.  #FPL changed the api and Vasstav has updated his libraries. Would you consider updating for the new season?

**Comment by antoniaelek** [comment]
Sure, I will do that. Thanks for letting me know.

**Comment by antoniaelek** [comment]
Data is now updated.

**Comment by jeski** [comment]
my lord, love the move to plotly. Well done!

**Comment by antoniaelek** [comment]
thanks @jeski. it does look fancier now, hoping to add more features, too 😄
